spring:
  redis:
    host: 127.0.0.1
    port: 6379

  mvc:
#    static-path-pattern: /static/**
    pathmatch:

      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 300MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#  web:
#    resources:
#      static-locations: file:/Users/mico/uploadFile/


rsa:
  public_str: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQAqsracQM5fc1KFHqBpRgjTIF5tmmsbePM2WpjJTTopHQGzr76o1uAKzsMVqHZ3/a1anBp3/ubqjCr0DFFOvCcVB6cShY6so5AAh5mF3bL1wLw+w8vp7nNFJMoV9EdVci6mYTodRkdIh5yAmVBTKf53oCiQnTQutt2Tu4XmjsxQIDAQAB
  private_str: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANACqytpxAzl9zUoUeoGlGCNMgXm2aaxt48zZamMlNOikdAbOvvqjW4ArOwxWodnf9rVqcGnf+5uqMKvQMUU68JxUHpxKFjqyjkACHmYXdsvXAvD7Dy+nuc0UkyhX0R1VyLqZhOh1GR0iHnICZUFMp/negKJCdNC623ZO7heaOzFAgMBAAECgYEAheFB1EZVtcuJicAywMKNW3tlN+E2MxDtSRDWnQLrgy9+VAhCtYNoleV/ZuH5F29pHispAIhTUd4NZoiv0mk9t5YPOWGRFL9iTmjugm9wPRJSDUka/Stwp1NS1X0+x7iK0iZpYM5Cuhz2P777TF0Ob58LiugL7SUx5RNu4kMVa70CQQDy+YpFXdn0ztLLfUk6QX6Q2ISNEcO5yVxoY5HzdXF+ydTXt+2FDkVudWH055LXxKQVF6SV9YPLjLjMucgwM/Z7AkEA2ylLxeNmzAnL3fTix+DxP2X67roMzfVk5sHFRPiiAgZ7bpAfsYk6UXsSA+XNFT1ONnfv0otDZnSGIHT23/jlvwJBAJ4KeknMVezKaoo5n9vope6JJw6rM2gw9Y5g1ZpKFdymY289D52wPrEuYNzvk7ANE700d7Wi0GshyUJAxVm1MukCQAkh+Glfp4n7Ioa2TLj9k7ALpOBL2nq+rhy7mGfeYInrETuzP87bJBX/JeoJqnknG9pDNzgz23QqiOhTV3JP4esCQBkxi+5FDdvEKbkQsDV/afwFRsyh/gWEChwQna11DS4AS1D0OZY2riC87w6HL5yCV35A4LCcC5gIX9hEWq5zM9w=
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

static:
  path: http://localhost:8080/static/

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true